---
- name: Remove old {{ sshconfig }} hosts entries for hosts
  delegate_to: localhost
  shell: |
    set -o pipefail
    {{ role_path }}/python/update_ssh_config.py {{ sshconfig }} --backup_file {{ sshconfig_backup }} --remove {{ hosts_comma }}
  args:
    executable: /bin/bash
  register: remove_entry
  changed_when: "remove_entry.rc == 0"
  run_once: true

- name: Add new {{ sshconfig }} hosts entries for hosts
  delegate_to: localhost
  shell: |
    set -o pipefail
    if [ -d .vagrant ]; then
        vagrant ssh-config | sed '/^[[:space:]]*$/d' >>  {{ sshconfig }}
    else
        echo You are not in a directory with a .vagrant directory
        exit 1
    fi
  args:
    executable: /bin/bash
    chdir: "{{ vagrant_dir }}"
  register: add_entry
  changed_when: "add_entry.rc == 0"
  run_once: true
